global:
  scrape_interval: 15s # 타겟 메트릭 수집 주기 (기본 1m → 여기선 15초마다 수집)
  evaluation_interval: 15s # 기록된 메트릭 기반 규칙(알람/레코딩 규칙) 평가 주기
scrape_configs:
  - job_name: "server"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8080"]
  - job_name: "ec2"
    static_configs:
      - targets: ["node_exporter:9100"]
