services:
  node_exporter:
    image: prom/node-exporter:latest # 현재 컴퓨터의 상태 즉, EC2의 매트릭 수집
    container_name: node_exporter
    ports:
      - "9100:9100" #EC2 서버(OS 레벨)의 CPU, 메모리, 디스크, 네트워크 등 메트릭을 수집해서 http://<EC2_IP>:9100/metrics 로 노출
    command:
      - "--path.rootfs=/host"
  promtail: # 로그를 수집해서 Loki에게 전달하는 역할
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ../logs:/var/log           # 호스트의 로그 폴더를 컨테이너 안 /var/log에 마운트 → promtail이 이 경로를 읽어서 로그를 수집
      - ../promtail:/etc/promtail  # promtail 설정 파일이 들어있는 폴더를 마운트 → promtail이 이 설정대로 동작
    command: -config.file=/etc/promtail/promtail-config.yml
