server:
  http_listen_port: 9080 # promtail 자체 메트릭/상태 확인용 HTTP 포트 (http://localhost:9080/metrics)
  grpc_listen_port: 0 # gRPC 비활성화 (0이면 사용 안 함)

positions:
  filename: /tmp/positions.yaml  # 로그 읽은 위치(offset)를 저장하는 파일 → 재시작 시 이어서 수집 가능

clients:
  - url: http://loki:3100/loki/api/v1/push # 수집한 로그를 전송할 Loki 서버의 주소

scrape_configs:
  - job_name: server-logs # 수집 작업(job) 이름 (라벨 job="server-logs"로 붙음)
    static_configs:
      - targets:
          - localhost # 대상 타겟 (실제 로그 파일 수집에는 의미 없음, 라벨링용)
        labels:
          job: server  # Loki에 저장될 job 라벨 값
          __path__: /var/log/*.log # 수집할 로그 파일 경로 패턴 (/var/log 아래의 *.log 파일들)

